(function() {var implementors = {};
implementors['collect'] = ["<a class='stability Stable' title='Stable'></a>impl&lt;'a, T: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> + 'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='collect/immut_slist/struct.Iter.html' title='collect::immut_slist::Iter'>Iter</a>&lt;'a, T&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;T&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='collect/immut_slist/struct.ImmutSList.html' title='collect::immut_slist::ImmutSList'>ImmutSList</a>&lt;T&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;K: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>, V: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='collect/proto/linear_map/struct.LinearMap.html' title='collect::proto::linear_map::LinearMap'>LinearMap</a>&lt;K, V&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;'a, K: 'a, V: 'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='collect/proto/linear_map/struct.Iter.html' title='collect::proto::linear_map::Iter'>Iter</a>&lt;'a, K, V&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;'a, K: 'a, V: 'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='collect/proto/linear_map/struct.Keys.html' title='collect::proto::linear_map::Keys'>Keys</a>&lt;'a, K, V&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;'a, K: 'a, V: 'a&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='collect/proto/linear_map/struct.Values.html' title='collect::proto::linear_map::Values'>Values</a>&lt;'a, K, V&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
