(function() {var implementors = {};
implementors['collect'] = ["<a class='stability Stable' title='Stable'></a>impl&lt;K, V, C&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/iter/trait.Extend.html' title='core::iter::Extend'>Extend</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.tuple.html'>(K, V)</a>&gt; for <a class='struct' href='collect/struct.TreeMap.html' title='collect::TreeMap'>TreeMap</a>&lt;K, V, C&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;T, C&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/iter/trait.Extend.html' title='core::iter::Extend'>Extend</a>&lt;T&gt; for <a class='struct' href='collect/struct.TreeSet.html' title='collect::TreeSet'>TreeSet</a>&lt;T, C&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;E: <a class='trait' href='collect/enum_set/trait.CLike.html' title='collect::enum_set::CLike'>CLike</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/iter/trait.Extend.html' title='core::iter::Extend'>Extend</a>&lt;E&gt; for <a class='struct' href='collect/enum_set/struct.EnumSet.html' title='collect::enum_set::EnumSet'>EnumSet</a>&lt;E&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;T, C: <a class='trait' href='compare/trait.Compare.html' title='compare::Compare'>Compare</a>&lt;T&gt;&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/iter/trait.Extend.html' title='core::iter::Extend'>Extend</a>&lt;T&gt; for <a class='struct' href='collect/interval_heap/struct.IntervalHeap.html' title='collect::interval_heap::IntervalHeap'>IntervalHeap</a>&lt;T, C&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;K, V, C&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/iter/trait.Extend.html' title='core::iter::Extend'>Extend</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.tuple.html'>(K, V)</a>&gt; for <a class='struct' href='collect/struct.TreeMap.html' title='collect::TreeMap'>TreeMap</a>&lt;K, V, C&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;T, C&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/iter/trait.Extend.html' title='core::iter::Extend'>Extend</a>&lt;T&gt; for <a class='struct' href='collect/struct.TreeSet.html' title='collect::TreeSet'>TreeSet</a>&lt;T, C&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
