(function() {var implementors = {};
implementors['collect'] = ["<a class='stability Unstable' title='Unstable: matches collection reform specification, waiting for dust to settle'></a>impl&lt;'a, 'b, T, C&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;&amp;'b <a class='struct' href='collect/struct.TreeSet.html' title='collect::TreeSet'>TreeSet</a>&lt;T, C&gt;, <a class='struct' href='collect/struct.TreeSet.html' title='collect::TreeSet'>TreeSet</a>&lt;T, C&gt;&gt; for &amp;'a <a class='struct' href='collect/struct.TreeSet.html' title='collect::TreeSet'>TreeSet</a>&lt;T, C&gt;","<a class='stability Unstable' title='Unstable: matches collection reform specification, waiting for dust to settle'></a>impl&lt;'a, 'b&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;&amp;'b <a class='struct' href='collect/struct.TrieSet.html' title='collect::TrieSet'>TrieSet</a>, <a class='struct' href='collect/struct.TrieSet.html' title='collect::TrieSet'>TrieSet</a>&gt; for &amp;'a <a class='struct' href='collect/struct.TrieSet.html' title='collect::TrieSet'>TrieSet</a>","<a class='stability Experimental' title='Experimental'></a>impl&lt;E: <a class='trait' href='collect/enum_set/trait.CLike.html' title='collect::enum_set::CLike'>CLike</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;<a class='struct' href='collect/enum_set/struct.EnumSet.html' title='collect::enum_set::EnumSet'>EnumSet</a>&lt;E&gt;, <a class='struct' href='collect/enum_set/struct.EnumSet.html' title='collect::enum_set::EnumSet'>EnumSet</a>&lt;E&gt;&gt; for <a class='struct' href='collect/enum_set/struct.EnumSet.html' title='collect::enum_set::EnumSet'>EnumSet</a>&lt;E&gt;","<a class='stability Unstable' title='Unstable: matches collection reform specification, waiting for dust to settle'></a>impl&lt;'a, 'b, T, C&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;&amp;'b <a class='struct' href='collect/struct.TreeSet.html' title='collect::TreeSet'>TreeSet</a>&lt;T, C&gt;, <a class='struct' href='collect/struct.TreeSet.html' title='collect::TreeSet'>TreeSet</a>&lt;T, C&gt;&gt; for &amp;'a <a class='struct' href='collect/struct.TreeSet.html' title='collect::TreeSet'>TreeSet</a>&lt;T, C&gt;","<a class='stability Unstable' title='Unstable: matches collection reform specification, waiting for dust to settle'></a>impl&lt;'a, 'b&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;&amp;'b <a class='struct' href='collect/struct.TrieSet.html' title='collect::TrieSet'>TrieSet</a>, <a class='struct' href='collect/struct.TrieSet.html' title='collect::TrieSet'>TrieSet</a>&gt; for &amp;'a <a class='struct' href='collect/struct.TrieSet.html' title='collect::TrieSet'>TrieSet</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
